bpruitt-goddard/vscode-mermaid-syntax-highlight

CHANGELOG.md
README.md
package.json
syntaxes/codeblock.json

Fixes issue #10 . Registers `Mermaid` language and links `.mmd` files. Moved the grammar into a separate variable to allow for it to be picked up both raw (in `mmd` files) and nested in markdown fencing.

Mmd file support

---

build/ConvertYaml.js

In previous version build was not working on Ubuntu. This should be fixed now.

Fix build process on Ubuntu

---

CHANGELOG.md
package.json

The `prepublish` script was using the wrong script name, thus not triggering when publishing the extension. The proper name is found from [these docs](https://code.visualstudio.com/api/working-with-extensions/publishing-extension#prepublish-step).

Correct prepublish script name

---

package.json

Hello. Thank you for providing really great extension!
I found the grammar isn't applied correctly in a `.mmd ` file. It seems to be caused by the capital letter in the language ID. I could confirm it worked fine at my local. I'm glad if this PR helps to improve this package.

modify "contributes.languages.id" in order to apply the grammar to .mmd files correctly

---

.github/workflows/master-merge.yml

Stop dealing with manual local deploys when Github Actions can handle it.
This action is deployed on PR merges. To avoid issues of trying to publish a duplicate version (such as when a PR is merged that does **not** bump the version), this action only runs when the `CHANGELOG.md` file is updated (inferring that a new version must have been made).

Create Github Action To Auto-Deploy

---

CHANGELOG.md
package.json
syntaxes/diagrams/sequenceDiagram.yaml
tests/diagrams/sequence.test.mermaid

Fixes whitespace in title for #76 
Fixes whitespace in participant/actors for #43

Fix Sequence Title and Participant Whitespace

---

.github/workflows/github-pr.yml
CHANGELOG.md
CONTRIBUTING.md
README.md
build/ConvertYaml.js
build/CustomYamlTypes.js
syntaxes/diagrams/classDiagram.yaml
syntaxes/diagrams/erDiagram.yaml
syntaxes/diagrams/ganttDiagram.yaml
syntaxes/diagrams/gitGraph.yaml
syntaxes/diagrams/graph.yaml
syntaxes/diagrams/pieChart.yaml
syntaxes/diagrams/stateDiagram.yaml

Add prettier validation to all `markdown`, `js`, and `yaml` files. `mermaid` files (used for tests) are not supported by prettier.

Add Prettier Validation To Github PR Workflow

---

syntaxes/diagrams/stateDiagram.yaml
tests/diagrams/state-v2.test.mermaid
tests/diagrams/state.test.mermaid

Fix the highlighting issues in #55.
* Be more flexible in note and transition text. Both should highlight the rest of the line aside from colons(:).
* Add support for v2 diagram name (`stateDiagram-v2`)

Fix State Diagram Note/Transition Text

---

CHANGELOG.md
package.json
syntaxes/diagrams/graph.yaml
tests/diagrams/graph.test.mermaid

This is to add multiline support called out in #64.
In order to add multiline support. the graph entities and graph links needed to be re-structured. Previously, the graph links were dependent upon an entity first existing (hanging off of `begin`/`end` patterns identifying an entity). But multiline graph links now required multiple graph link patterns based upon whether the graph link spanned one line or multiple. If the graph link was a multiline text version it needed a different end pattern than a single line version.
With the previous entity structure, each entity pattern would need all of these graph patterns:
* (Entity From)
* (Graph Link Single Line)
* (Graph Link Multi Line)
* (Entity From)(Edge Shape)
* (Graph Link Single Line)
* (Graph Link Multi Line)
But this could still cause …

Add Graph Multiline Text Support

---

.github/workflows/github-pr.yml

The prettier action has a bug in the previous version that this new version fixes to allow the workflow to work again.

PR Workflow Github Action Version Bump

---

syntaxes/diagrams/ganttDiagram.yaml
tests/diagrams/gantt.test.mermaid

I've used this syntax plugin recently while developing Gantt diagramm and noticed it doesn't support `excludes` and `todayMarker` keywords. (#99)
`excludes` accepts specific dates in YYYY-MM-DD format, days of the week ("sunday") or "weekends", but not the word "weekdays":
- [Playground, excludes with multiple dates and days combined](https://mermaid.live/edit#pako:eNplkk1v2zAMhv8KQaBAC8iBPxLH9i1Y0J7SS3vZoEM1i86E2pJhyVuzIP99stSuGcYTwY-H5CudsTWSsMGj0M5xDd6kcHRvpkE4gK_eksMh2e9jzinXE0TbSan0ER52j8_PIJU4TmKAbtatU0aLXrkTOAMDeZKSsZ3e2n6WZBc_T7N1kmZJWrFPv2bwi-iVtLSx4-YGbl8-2l5AtC2NzoIdqVWdasOyFpS-2hS6sDzzuZMF04H7QYEKtxztrH2Y4x2YCTj-HYYMvs8OtHGx3EzyPb1QOK7uuI4bWQoHwu7Di-EvZhh7ciTBCfsKV9ZIo4kFZclmV8eW7FODCNl54E_6j7BAREixAMn_Vazw6iLDd6X9Y54XGkd_yEAcG-9K6sTcO45cX3ypmJ15OukWGzfNxHAeFx338Q2x6URvfXQUGpsz …

Add excludes and todayMarker keywords for Gantt diagramm

---

syntaxes/diagrams/ganttDiagram.yaml
tests/diagrams/gantt.test.mermaid

Fixes #100 
[Regex playground](https://regex101.com/r/anOH3S/1)
[Mermaid playground](https://mermaid.live/edit#pako:eNplUcFuwjAM_ZXIErcSmrSUkhsa2o3TdtmUS0QMVGsT1LoTDPHvc9uhTdo7vTz7vVj2DfbRIxg4ukBkg2BQRTWKV-x-3t4RPse2cSTEdit3O_nGmGruUnWP2mLmpSS80GIxayyDOGI-n11tmJo73FMVg9g82CQ_xeZcI6EX5LoP8QfGx4DJwNJCpkrqVOWJSMsHn_wbzvrEf-bB78YSJ3jsNDvXvymZtwESaJCHrzxv4DakWaATNmjBMPV4cH1NFmy4c6vrKb5cwx4MtT0m0J-HzWwrd2xdA-bg6o7VswtgbnABMy9zWahVmWmda1UUSidwBaOzUuZluWZhqdNiVWT3BL5i5AglM7VWLJdKpcs0V8sE0FcU2910pfFY4x_vo2EY5P4Nd9OBmA) (also a proof that it's a valid usecase)

fix: add better regex for dateFormat and axisFormat

---

syntaxes/diagrams/sequenceDiagram.yaml
tests/diagrams/sequence.test.mermaid

Fixes #90. The problem wasn't with the `end` keyword, but the way the Actor was being matched. In this case, it didn't properly handle ending parentheses, which caused the whole line to not be treated as a proper "(Actor)(Arrow)(Actor)(:)(Message)" line and thus fallback to only looking for `end` within the line.
With the change, this line is properly highlighted:

Sequence Actors Match Ending Parentheses

---

CHANGELOG.md
build/ConvertYaml.js
build/CustomYamlTypes.js
package.json
syntaxes/diagrams/sequenceDiagram.yaml
tests/diagrams/sequence.test.mermaid

Adds support for `critical` keyword in sequence diagrams:
Also bumps version to push out latest changes.
Fixes #107

Add Sequence Critical Keyword Support

---

syntaxes/diagrams/classDiagram.yaml
tests/diagrams/class.test.mermaid

Previously, they would only work separately, now they work if a method is both. This fixes #70 .

Update Clas Diagram Abstract Static Method Support

---

syntaxes/mermaid.tmLanguage-markdown.yaml
tests/markdown/with-attributes.test.mermaid

PR implementing the functionality from https://github.com/bpruitt-goddard/vscode-mermaid-syntax-highlight/pull/92#discussion_r1375132354, but addressing the comment and merge conflict. Thank you @mattorp for the work.

Support pandoc syntax

---

syntaxes/diagrams/sequenceDiagram.yaml
tests/diagrams/sequence.test.mermaid

This adds a new rule + test coverage for capturing the `box` keyword as described in the docs here:
https://mermaid.js.org/syntax/sequenceDiagram.html#grouping-box
Resolves this scenario:

syntax: add box keyword for sequenceDiagram

---

syntaxes/diagrams/ganttDiagram.yaml
tests/diagrams/gantt.test.mermaid

tickInterval was an option in gannt, added it to the ganntDiagram.yaml syntax.

feat: Add syntax for tickInterval in gannt diagram

---

CHANGELOG.md
package.json
syntaxes/diagrams/graph.yaml
tests/diagrams/graph.test.mermaid

Fixes the text issues in graph for #98. This fixes the below two issues and adds tests to verify:
Normal entity text:
Subgraph:
This also bumps the version to deploy the latest changes.

Fix Graph Html Text

---

build/CustomYamlTypes.js
syntaxes/diagrams/ganttDiagram.yaml
syntaxes/diagrams/gitGraph.yaml
syntaxes/diagrams/graph.yaml
syntaxes/diagrams/pieChart.yaml
syntaxes/diagrams/quadrantChart.yaml
syntaxes/diagrams/requirementDiagram.yaml
syntaxes/diagrams/sequenceDiagram.yaml
syntaxes/diagrams/stateDiagram.yaml
syntaxes/diagrams/userJourney.yaml
tests/diagrams/gantt.test.mermaid
tests/diagrams/gitGraph.test.mermaid
tests/diagrams/graph.test.mermaid
tests/diagrams/pie.test.mermaid
tests/diagrams/quadrantChart.test.mermaid
tests/diagrams/state.test.mermaid
tests/diagrams/userJourney.test.mermaid

Fixes #131 , but also extends this support to all keywords across all diagrams. I hadn't previously realized, but in order to make keyword matching case-insensitive, the associated regex flag `(?i)` needs to be applied to _each_ line in the tmgrammar file.  Fortunately, with the existing custom yaml converter this can be done automatically when building the json language file. 
Once this was added, it was observed that it is possible for some keywords to match in the middle of a line when they should only match at the start of the line. The regexes were updated to only match at the beginning of a line (aside from whitespace), and negative tests were generated to ensure that they do not highlight in this case.

Highlight Case Insensitive Keywords

---

CHANGELOG.md
package.json
syntaxes/diagrams/graph.yaml
tests/diagrams/graph.test.mermaid

The subgraph direction was not properly highlighting:
This PR fixes the highlighting:
It also bumps the versioning to include both this change and the last PR #134 .

Fix Graph Subgraph Direction

---

.github/workflows/master-merge.yml

The github action for performing a deployment was triggering on a pull request merge. But this was being done within the context of the source branch, which does not have access to the repository's secrets. Namely the access token for deploying a new version of the extension.
Instead of basing this action on the PR merge, this new approach bases on a push to the master branch, which should always operate within the context of someone with access to the secrets. See [this github discussion](https://github.com/orgs/community/discussions/25588).
This shouldn't change _when_ the deployments happen, it should simply allow the action to have access to the necessary secret.

Fix Github Action Deployment

---

CHANGELOG.md
package-lock.json
package.json
syntaxes/mermaid.tmLanguage-mdx.yaml
tests/markdown/mdx.test.mdx

This injects the `mermaid` grammar into MDX code blocks annotated with the `mermaid` language.

feat(mdx): add MDX grammar injection

---

.github/workflows/github-pr.yml
.github/workflows/master-merge.yml
CONTRIBUTING.md
build/ConvertYaml.mjs
build/CustomYamlTypes.mjs
package-lock.json
package.json

Updates dependencies including to latest Node LTS.  Latest version of `yaml-import` now only supports ESM, so also migrates to using import syntax.
Adjusts the contributing document to reference the new name of the vsce CLI package.

Update dependencies and use ESM

---

CHANGELOG.md
package.json
syntaxes/diagrams/graph.yaml
tests/diagrams/graph-flowchart.test.mermaid
tests/diagrams/graph.test.mermaid

- Adds support for extended node shapes
- Also adds support for implicit graph direction as mermaid allows it (and defaults to TB)
Before:
<details><summary>Screenshots</summary>
</details>
After:
<details><summary>Screenshots</summary>
</details>

feat: (graph) support extended node shapes

---

CHANGELOG.md
package.json
syntaxes/diagrams/graph.yaml
tests/diagrams/graph.test.mermaid

Adds support for a dotted link syntax variation without leading dash (`-.->` & `.->` are both valid) as well as support for arrow label `|Text|` notation without `>` symbol
Before:
<details><summary>Screenshots</summary>
</details>
After:
<details><summary>Screenshots</summary>
</details>

fix: dotted graph links syntax
